# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-21 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='main_user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='main_user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='main_user',
        ),
    ]
